on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      uses: actions/setup-node@v1
      with:
        node-version: '8.10.0'
      run: |
        yarn install
        yarn lint
        yarn build
        yarn test:coverage
      env:
        CI: true